interface ItemType { name: string, icon?: string }

// ! GADGETS
export const gadgets = {
  // ? common
  flashbang: { name: 'Flashbang', icon: 'i-game-icons:stun-grenade' },
  frag_grenade: { name: 'Frag Grenade', icon: 'i-game-icons:grenade' },
  gas_grenade: { name: 'Gas Grenade', icon: 'i-game-icons:poison-gas' },
  goo_grenade: { name: 'Goo Grenade', icon: 'i-game-icons:goo-explosion' },
  pyro_grenade: { name: 'Pyro Grenade', icon: 'i-game-icons:fire-bomb' },
  smoke_grenade: { name: 'Smoke Grenade', icon: 'i-game-icons:smoke-bomb' },
  // ? light
  glitch_grenade: { name: 'Glitch Grenade', icon: 'i-game-icons:bolt-bomb' },
  sonar_grenade: { name: 'Sonar Grenade', icon: 'i-game-icons:satellite-communication' },
  breach_charge: { name: 'Breach Charge', icon: 'i-game-icons:dynamite' },
  gateway: { name: 'Gateway', icon: 'i-game-icons:portal' },
  stun_gun: { name: 'Stun Gun', icon: 'i-game-icons:electrical-resistance' },
  thermal_bore: { name: 'Thermal Bore', icon: 'i-game-icons:steyr-aug' },
  thermal_vision: { name: 'Thermal Vision', icon: 'i-game-icons:eye-target' },
  tracking_dart: { name: 'Tracking Dart', icon: 'i-game-icons:steyr-aug' },
  vanishing_bomb: { name: 'Vanishing Bomb', icon: 'i-game-icons:invisible' },
  gravity_vortex: { name: 'Gravity Vortex', icon: 'i-game-icons:vortex' },
  heal_infuser: { name: 'H+ Infuser', icon: 'i-game-icons:health-capsule' },
  // ? medium
  aps_turret: { name: 'APS Turret', icon: 'i-game-icons:shield-reflect' },
  data_reshaper: { name: 'Data Reshaper', icon: 'i-game-icons:database' },
  defibrillator: { name: 'Defibrillator', icon: 'i-game-icons:heart-beats' },
  explosive_mine: { name: 'Explosive Mine', icon: 'i-game-icons:land-mine' },
  gas_mine: { name: 'Gas Mine', icon: 'i-game-icons:land-mine' },
  glitch_trap: { name: 'Glitch Trap', icon: 'i-game-icons:box-trap' },
  jump_pad: { name: 'Jump Pad', icon: 'i-game-icons:jump-across' },
  proximity_sensor: { name: 'Proximity Sensor', icon: 'i-game-icons:movement-sensor' },
  zipline: { name: 'Zipline', icon: 'i-game-icons:zipper' },
  breach_drill: { name: 'Breach Drill', icon: 'i-game-icons:drill' },
  // ? heavy
  anti_gravity_cube: { name: 'Anti-Gravity Cube', icon: 'i-game-icons:cube' },
  barricade: { name: 'Barricade', icon: 'i-game-icons:defensive-wall' },
  c4: { name: 'C4', icon: 'i-game-icons:dynamite' },
  dome_shield: { name: 'Dome Shield', icon: 'i-game-icons:viking-shield' },
  lockbolt: { name: 'Lockbolt', icon: 'i-game-icons:combination-lock' },
  pyro_mine: { name: 'Pyro Mine', icon: 'i-game-icons:land-mine' },
  rpg_7: { name: 'RPG-7', icon: 'i-game-icons:missile-launcher' },
  heal_emitter: { name: 'Heal Emitter', icon: 'i-game-icons:healing' },
} satisfies Record<string, ItemType>

// ! WEAPONS
export const weapons = {
  // ? light
  '93_r': { name: '93R', icon: 'i-game-icons:pistol-gun' },
  'dagger': { name: 'Dagger', icon: 'i-game-icons:plain-dagger' },
  'lh1': { name: 'LH1', icon: 'i-game-icons:steyr-aug' },
  'm11': { name: 'M11', icon: 'i-game-icons:m3-grease-gun' },
  'm26_matter': { name: 'M26 Matter', icon: 'i-game-icons:sawed-off-shotgun' },
  'recursive_bow': { name: 'Recursive Bow', icon: 'i-game-icons:high-shot' },
  'sh1900': { name: 'SH1900', icon: 'i-game-icons:blunderbuss' },
  'sr_84': { name: 'SR-84', icon: 'i-game-icons:steyr-aug' },
  'sword': { name: 'Sword', icon: 'i-game-icons:katana' },
  'throwing_knives': { name: 'Throwing Knives', icon: 'i-game-icons:thrown-daggers' },
  'v9_s': { name: 'V9S', icon: 'i-game-icons:pistol-gun' },
  'xp_54': { name: 'XP-54', icon: 'i-game-icons:mac-10' },
  // ? medium
  'akm': { name: 'AKM', icon: 'i-game-icons:ak47' },
  'cerberus_12_ga': { name: 'Cerberus 12GA', icon: 'i-game-icons:sawed-off-shotgun' },
  'cl_40': { name: 'CL-40', icon: 'i-game-icons:pirate-cannon' },
  'dual_blades': { name: 'Dual Blades', icon: 'i-game-icons:crossed-swords' },
  'famas': { name: 'Famas', icon: 'i-game-icons:famas' },
  'fcar': { name: 'Fcar', icon: 'i-game-icons:ak47u' },
  'model_1887': { name: 'Model 1887', icon: 'i-game-icons:lee-enfield' },
  'pike_556': { name: 'Pike-556', icon: 'i-game-icons:steyr-aug' },
  'r_357': { name: 'R .357', icon: 'i-game-icons:colt-m1911' },
  'riot_shield': { name: 'Riot Shield', icon: 'i-game-icons:riot-shield' },
  // ? heavy
  '50_akimbo': { name: '.50 Akimbo', icon: 'i-game-icons:colt-m1911' },
  'flamethrower': { name: 'Flamethrower', icon: 'i-game-icons:flamethrower-soldier' },
  'ks_23': { name: 'KS-23', icon: 'i-game-icons:winchester-rifle' },
  'lewis_gun': { name: 'Lewis Gun', icon: 'i-game-icons:thompson-m1928' },
  'm60': { name: 'M60', icon: 'i-game-icons:thompson-m1928' },
  'mgl32': { name: 'MGL32', icon: 'i-game-icons:pirate-cannon' },
  'sa1216': { name: 'SA1216', icon: 'i-game-icons:mp-40' },
  'shak_50': { name: 'Shak-50', icon: 'i-game-icons:ak47u' },
  'sledgehammer': { name: 'Sledgehammer', icon: 'i-game-icons:thor-hammer' },
  'spear': { name: 'Spear', icon: 'i-game-icons:spears' },
} satisfies Record<string, ItemType>

// ! SPECIALIZATIONS
export const specializations = {
  // ? light
  cloaking_device: { name: 'Cloaking Device', icon: 'i-game-icons:invisible' },
  evasive_dash: { name: 'Evasive Dash', icon: 'i-game-icons:fire-dash' },
  grappling_hook: { name: 'Grappling Hook', icon: 'i-game-icons:grapple' },
  // ? medium
  dematerializer: { name: 'Dematerializer', icon: 'i-game-icons:circuitry' },
  guardian_turret: { name: 'Guardian Turret', icon: 'i-game-icons:tesla-turret' },
  healing_beam: { name: 'Healing Beam', icon: 'i-game-icons:healing' },
  // ? heavy
  charge_n_slam: { name: 'Charge \'n\' Slam', icon: 'i-game-icons:shield-bash' },
  goo_gun: { name: 'Goo Gun', icon: 'i-game-icons:grouped-drops' },
  mesh_shield: { name: 'Mesh Shield', icon: 'i-game-icons:shieldcomb' },
  winch_claw: { name: 'Winch Claw', icon: 'i-game-icons:bird-claw' },
} satisfies Record<string, ItemType>

export const classes: {
  name: string
  specializations: (keyof typeof specializations)[]
  weapons: (keyof typeof weapons)[]
  gadgets: (keyof typeof gadgets)[]
}[] = [
  {
    name: 'Light',
    specializations: [
      'cloaking_device',
      'evasive_dash',
      'grappling_hook',
    ],
    weapons: [
      '93_r',
      'dagger',
      'lh1',
      'm11',
      'm26_matter',
      'recursive_bow',
      'sh1900',
      'sr_84',
      'sword',
      'throwing_knives',
      'v9_s',
      'xp_54',
    ],
    gadgets: [
      'breach_charge',
      'flashbang',
      'frag_grenade',
      'gas_grenade',
      'gateway',
      'glitch_grenade',
      'goo_grenade',
      'pyro_grenade',
      'smoke_grenade',
      'sonar_grenade',
      'stun_gun',
      'thermal_bore',
      'thermal_vision',
      'tracking_dart',
      'vanishing_bomb',
      'gravity_vortex',
    ],
  },
  {
    name: 'Medium',
    specializations: [
      'dematerializer',
      'guardian_turret',
      'healing_beam',
    ],
    weapons: [
      'akm',
      'cerberus_12_ga',
      'cl_40',
      'dual_blades',
      'famas',
      'fcar',
      'model_1887',
      'pike_556',
      'r_357',
      'riot_shield',
    ],
    gadgets: [
      'aps_turret',
      'data_reshaper',
      'defibrillator',
      'explosive_mine',
      'flashbang',
      'frag_grenade',
      'gas_grenade',
      'gas_mine',
      'glitch_trap',
      'goo_grenade',
      'jump_pad',
      'proximity_sensor',
      'pyro_grenade',
      'smoke_grenade',
      'zipline',
    ],
  },
  {
    name: 'Heavy',
    specializations: [
      'charge_n_slam',
      'goo_gun',
      'mesh_shield',
      'winch_claw',
    ],
    weapons: [
      '50_akimbo',
      'flamethrower',
      'ks_23',
      'lewis_gun',
      'm60',
      'mgl32',
      'sa1216',
      'shak_50',
      'sledgehammer',
      'spear',
    ],
    gadgets: [
      'anti_gravity_cube',
      'barricade',
      'c4',
      'dome_shield',
      'explosive_mine',
      'flashbang',
      'frag_grenade',
      'gas_grenade',
      'goo_grenade',
      'lockbolt',
      'proximity_sensor',
      'pyro_grenade',
      'pyro_mine',
      'rpg_7',
      'smoke_grenade',
      'heal_emitter',
    ],
  },
]
